// v0.16 regression protection: restore features that must survive every update.
UI.hiredFailed=why=>UI.overlay(`<h3>雇人代送失败</h3><p>${why==='fish'?'古代背囊里没有鱼，今天无法代送。':'古代钱不足4文，付不起跑腿费。'}</p><button class="btn primary" onclick="S.supply.li.mode='manual';C.rumor('今日任务：雇人送鱼失败，请亲自给酒楼送至少1条鱼。');UI.close()">今天改为自己送</button><button class="btn" onclick="UI.close()">暂时不管</button>`);
UI.refundModern=id=>{if(!S.modern)return UI.toast('只有还在现代便利店时才能退回商品');if(!S.bags.travel.items[id])return;if(C.remove(S.bags.travel,id)){S.rmb+=D.items[id].price;C.refresh();UI.toast(`退回${D.items[id].name}，退款¥${D.items[id].price}`)}UI.bags()};
const _inv=UI.inv;UI.inv=(n,i,type)=>`<div class="card"><b>${n} · ${C.slots(i)}/${i.cap}格</b>${Object.entries(i.items).map(([k,v])=>`<div class="slot">${D.items[k].name} ×${v}${type==='travel'?` <button class="movebtn" onclick="UI.moveBag('${k}','travel','ancient')">→古代</button>${S.modern&&D.items[k].world==='modern'?` <button class="movebtn" onclick="UI.refundModern('${k}')">退货</button>`:''}`:''}${type==='ancient'?` <button class="movebtn" onclick="UI.moveBag('${k}','ancient','travel')">→穿越</button>${D.items[k].food?` <button class="movebtn" onclick="C.eat();UI.bags()">吃</button>`:''}`:''}</div>`).join('')||'<p class="muted">空</p>'}</div>`;
UI.liCard=()=>{let q=S.supply.li,n=['未合作','试供','稳定供货','固定供应'][q.stage];return `<div class="card"><h3>酒楼供货：${n}</h3>${q.stage?`<p>每天至少1条鱼 · 今日${q.delivered?'已完成':'未完成'}</p>`:''}${q.stage>=2?`<button class="btn" onclick="UI.supplyMode()">方式：${q.mode==='manual'?'自己送':'10:00雇人代送'}</button>`:''}</div>`};
UI.wangCard=()=>{let w=S.work.wang,n=['未开始','固定帮工','学徒','独立做活'][w.stage];return `<div class="card"><h3>木匠线：${n}</h3>${w.stage?`<p>每3天至少做2次 · 本轮 ${w.daysThisCycle}/2</p><button class="btn" onclick="UI.workWang()">今天跟着做活</button>`:''}</div>`};
UI.supplyMode=()=>UI.overlay(`<h3>供货方式</h3><button class="btn" onclick="S.supply.li.mode='manual';C.rumor('今日任务：亲自给酒楼送至少1条鱼。');UI.close();UI.npc('li')">自己送</button><button class="btn" onclick="S.supply.li.mode='hired';UI.close();UI.npc('li')">10:00雇人代送 · 4文/天</button>`);
UI.workWang=()=>{let w=S.work.wang;if(w.workedToday)return UI.toast('今天已经做过木匠活');if(S.energy<14)return UI.toast('体力不够');C.advance(w.stage>=2?180:150,14);w.workedToday=true;w.daysThisCycle++;S.skills.wood+=w.stage>=2?2:1;S.money+=w.stage>=2?18:12;S.aff.wang+=2;UI.toast('今天的木匠活完成');UI.npc('wang')};
const _npc=UI.npc;UI.npc=id=>{let arr=D.chat[id]||[['闲聊','“今天没什么特别的。”']],idx=(S.memory[id]?.chat||0)%arr.length,d=arr[idx];S.memory[id]=S.memory[id]||{};S.memory[id].chat=idx+1;let items=Object.keys({...S.bags.ancient.items,...S.bags.travel.items});let special=id==='li'?UI.liCard():id==='wang'?UI.wangCard():'';UI.render(`<div class="hero"><h2>${D.npcs[id][0]} ♥${S.aff[id]}</h2><p>${d[0]}</p></div>${special}<div class="card"><p>${d[1]}</p><button class="btn" onclick="UI.chat('${id}','${d[0]}')">继续聊</button></div><div class="card"><h3>拿东西给他/她看</h3>${items.map(k=>`<button class="btn" onclick="UI.showItem('${id}','${k}')">${D.items[k].name}</button>`).join('')||'<p>没有东西。</p>'}</div><button class="btn" onclick="UI.place('${S.place}')">离开</button>`)};
UI.field=()=>UI.render(`<div class="hero"><h2>镇外菜地</h2></div>${S.plots.map((p,i)=>{if(!p)return `<div class="card"><b>空地</b><button class="btn" onclick="UI.plant(${i})">播种</button></div>`;let c=D.crops[p.seed],ready=S.day-p.day>=c[1];return `<div class="card"><b>${c[0]}</b><p>${ready?'已经成熟':p.tendedToday?'今天已照料':'今天还没照料'}</p>${ready?`<button class="btn primary" onclick="UI.harvest(${i})">收获</button>`:`<button class="btn" onclick="UI.tend(${i})">浇水除草</button>`}</div>`}).join('')}<button class="btn" onclick="UI.place('field')">返回</button>`);
UI.harvest=i=>{let p=S.plots[i],c=D.crops[p.seed],id=c[2],n=c[3];if(!C.canAdd(S.bags.ancient,id,Math.min(n,2)))return UI.toast('古代背囊放不下收成');let got=Math.min(n,2);C.add(S.bags.ancient,id,got);S.plots[i]=null;S.skills.farming+=2;UI.toast(`收获${D.items[id].name} ×${got}`);UI.field()};
UI.saveMenu=()=>UI.overlay(`<h3>游戏</h3><button class="btn primary" onclick="C.save()">保存游戏</button><button class="btn" onclick="UI.title()">返回标题</button>`);
