window.DATA={
items:{
pencil:{name:'铅笔',price:2,stack:4,type:'tool'},soap:{name:'肥皂',price:5,stack:3,type:'tool'},bandage:{name:'创可贴',price:5,stack:5,type:'tool'},lighter:{name:'打火机',price:2,stack:2,type:'tool'},sugar:{name:'白糖',price:6,stack:3,type:'food'},pen:{name:'圆珠笔',price:3,stack:4,type:'tool'},mirror:{name:'小镜子',price:8,stack:2,type:'tool'},plastic:{name:'塑料袋',price:3,stack:8,type:'tool'},bread:{name:'馒头',price:2,stack:4,type:'food',hunger:18,energy:5},noodle:{name:'方便面',price:5,stack:2,type:'food',hunger:28,energy:8}
},
npcs:{
wang:{name:'王木匠',job:'木匠',aff:8,align:'neutral',place:'carpenter'},ahe:{name:'阿禾',job:'木匠之女',aff:12,align:'good',place:'carpenter'},suwan:{name:'苏婉',job:'药铺学徒',aff:6,align:'good',place:'pharmacy'},li:{name:'李大厨',job:'酒楼厨师',aff:2,align:'neutral',place:'restaurant'},zhou:{name:'周掌柜',job:'杂货铺掌柜',aff:1,align:'neutral',place:'store'},chen:{name:'陈先生',job:'书铺掌柜',aff:2,align:'neutral',place:'book'},liu:{name:'刘婶',job:'洗衣妇',aff:9,align:'good',place:'river'},xiaobao:{name:'小宝',job:'小乞儿',aff:15,align:'good',place:'temple'},ergou:{name:'二狗',job:'混混',aff:0,align:'bad',place:'lane'},sunpo:{name:'孙婆婆',job:'卖饼老妇',aff:10,align:'good',place:'lane'},qianzi:{name:'钱四',job:'赌徒',aff:3,align:'bad',place:'lane'},zhao:{name:'赵捕头',job:'捕头',aff:0,align:'neutral',place:'market'}
},
locations:{temple:{name:'土地庙',npcs:['xiaobao'],distance:0},river:{name:'河边',npcs:['liu'],distance:12},lane:{name:'贫民巷',npcs:['sunpo','ergou','qianzi'],distance:10},market:{name:'集市',npcs:['zhao'],distance:18},carpenter:{name:'木匠坊',npcs:['wang','ahe'],distance:16},pharmacy:{name:'药铺',npcs:['suwan'],distance:17},restaurant:{name:'酒楼',npcs:['li'],distance:20},store:{name:'杂货铺',npcs:['zhou'],distance:18},book:{name:'书铺',npcs:['chen'],distance:19},hill:{name:'后山',npcs:[],distance:15}},
chat:{
wang:[['活计','最近木料多得很，一个人忙不过来。'],['手艺','做木匠最先学的不是锯，是看料。'],['镇里生意','有钱人最近爱定做箱柜。']],
ahe:[['河边','刘婶今天又在说谁家的闲话。'],['画画','我有时候会在废木头上乱画。'],['父亲','我爹嘴硬，其实挺缺人帮忙。']],
suwan:[['伤口','最近来药铺包扎的人比往常多。'],['学医','很多东西不能只看偏方，得先弄明白。']],
li:[['吃食','最近客人嫌点心不够新鲜。'],['后厨','后厨缺人时可忙得脚不沾地。']],
zhou:[['做生意','稀奇货只卖一次不算本事，能稳定供货才算。'],['价格','同样东西，卖给不同人价可不一样。']],
chen:[['读书','纸笔只是工具，能不能写明白才重要。'],['镇闻','学堂最近在找便宜纸张。']],
liu:[['闲话','贫民巷的钱四昨晚又输光了。'],['洗衣','要是有更省力的去油法就好了。']],
xiaobao:[['吃的','我今天还没吃东西。'],['零活','集市那边偶尔有人招搬东西。']],
sunpo:[['饼','今天剩的饼不多。'],['小宝','那孩子嘴硬，饿了也不肯说。']],
ergou:[['地盘','这条巷子谁进谁出，我都看着呢。'],['钱','有钱就好说话。']],
qianzi:[['运气','今天我肯定能翻本。'],['借钱','你要是有闲钱……']],
zhao:[['治安','最近集市有人顺手牵羊。'],['夜里','晚上别一个人乱跑。']]
},
transport:{walk:{name:'步行',energyPerMin:.45,timeMul:1,cost:0},sedan:{name:'轿子',energyPerMin:.08,timeMul:.75,cost:8,locked:true},carriage:{name:'马车',energyPerMin:.05,timeMul:.55,cost:15,locked:true}},
skillNames:{wood:'木工',medicine:'医药',cooking:'烹饪',trade:'经商',literacy:'识文',social:'人情',survival:'生存',retail:'零售管理',hygiene:'现代卫生',management:'管理'}
};